### ISSUE TITLE
Change download location 

### ISSUE THREAD

**Issue by sledgemasterrrr** [michaelb/auto-ytdl#31]
Im downloading thousands of videos and want to change the location of the downloads to mass storage and not my SSD's how can i do this?

**Comment by sledgemasterrrr** [comment]
Also could you change this to use yt-dlp instead of yt-dl for the enhanced speeds

**Comment by michaelb** [comment]
> downloading thousands of videos 

Hmmm. auto-ytdl is probably not very adapted to this use case. It's made specifically to update a _music_ collection with the few songs that have been released since the last time auto-ytdl ran.

It's _not_ fully automatic, meaning that sometime there will be a few blocking ,prompts and it's got several features specifically preventing it to download too many, too big, too lenghty, not-music-like-named things

**Comment by sledgemasterrrr** [comment]
> > downloading thousands of videos 
> 
> Hmmm. auto-ytdl is probably not very adapted to this use case. It's made specifically to update a _music_ collection with the few songs that have been released since the last time auto-ytdl ran.
> 
> It's _not_ fully automatic, meaning that sometime there will be a few blocking ,prompts and it's got several features specifically preventing it to download too many, too big, too lenghty, not-music-like-named things

I meant music not videos, how would I go about changing to where the audio is downloaded? I want it to download on the drive the program is installed in and not my c drive

**Comment by michaelb** [comment]
In the config.toml, you should be able to change the key "library path" to another location, such as
"D:\Music"

This configuration file is created at the first aytfl launch in your Documents/aytdl folder.


You'd better modify the max-downloads and playlist-end value to higher values while you're there.

Mind however, that the files will transit by a temporary folder that might inevitably be on your system drive

> Youtube-dlp ?

Short answer: no, since i'm unable to re-package a .exe for windows, having no windows machine

Long answer: Under the hood, there's no reason why it can't be changed. However, if you lack the knowledge to do figure that out yourself, I'll probably lack the patience to explain it to you (my time is not free, either). All your potential issues can be fixed too, but at that point let me reassert that maybe auto-ytdl isn't the best tool for the job

**Comment by sledgemasterrrr** [comment]
> In the config.toml, you should be able to change the key "library path" to another location, such as "D:\Music"
> 
> This configuration file is created at the first aytfl launch in your Documents/aytdl folder.
> 
> You'd better modify the max-downloads and playlist-end value to higher values while you're there.
> 
> Mind however, that the files will transit by a temporary folder that might inevitably be on your system drive
> 
> > Youtube-dlp ?
> 
> Short answer: no, since i'm unable to re-package a .exe for windows, having no windows machine
> 
> Long answer: Under the hood, there's no reason why it can't be changed. However, if you lack the knowledge to do figure that out yourself, I'll probably lack the patience to explain it to you (my time is not free, either). All your potential issues can be fixed too, but at that point let me reassert that maybe auto-ytdl isn't the best tool for the job

i understand thank you for taking the time to respond and help me with this issue!
